variables:
    PATH_TO_JAR:    /target/*.jar
    #IP:             10.128.0.13
    #IP: $ENV-VARIEBLE
    
stages:
    - build
    - deploy    
    - update
    

.build_template: &build_template
    stage: build
    script:
        - cd $PATH_TO_APP
        - mvn clean package
        - sudo docker build -t gitlab.svagworks.me:5050/root/demo_3:$PATH_TO_APP .
        - sudo docker push gitlab.svagworks.me:5050/root/demo_3:$PATH_TO_APP
    artifacts:
        paths:
        - $PATH_TO_APP$PATH_TO_JAR
        expire_in: 5 min

build_messaging:
    <<: *build_template
    variables:
        PATH_TO_APP: messaging
    only:
        changes:
            - messaging/**/*
        
build_payment:
    <<: *build_template
    variables:
       PATH_TO_APP: payment
    only:
        changes:
           - payment/**/*

build_simulation:
    <<: *build_template
    variables:
        PATH_TO_APP: simulation     
    only:
        changes:
            - simulation/**/*

build_trip:
    <<: *build_template
    variables:
        PATH_TO_APP: trip     
    only:
        changes:
            - trip/**/*

build_vehicle:
    <<: *build_template
    variables:
        PATH_TO_APP: vehicle     
    only:
        changes:
            - vehicle/**/*

build_identity:
    stage: build
    script:
        - cd identity/identity-starter && mvn clean install
        - cd ../identity-service && mvn clean package
        - sudo docker build -t gitlab.svagworks.me:5050/root/demo_3:identity .
        - sudo docker push gitlab.svagworks.me:5050/root/demo_3:identity
    artifacts:
        paths:
        - identity/identity-starter$PATH_TO_JAR
        - identity/identity-service$PATH_TO_JAR
        expire_in: 1 day 
    only:
        changes:
            - identity/**/*

.deploy_template: &deploy_template
    stage: deploy
    script:
      - scp -r /home/env docker-compose.yml deploy.sh $USERNAME@$IP_TEST:/tmp
      - ssh $USERNAME@$IP_TEST "sudo cp -r /tmp/env /var/ && sudo mv /tmp/docker-compose.yml /var/ && sudo mv /tmp/deploy.sh /var/"
      - ssh $USERNAME@$IP_TEST "cd /var/ && sudo bash /var/deploy.sh"
      
deploy_identity:
    <<: *deploy_template
    only:
        changes:
            - identity/**/*

deploy_messaging:
    <<: *deploy_template
    only:
        changes:
            - messaging/**/*
        
deploy_payment:
    <<: *deploy_template
    only:
        changes:
            - payment/**/*
        
deploy_simulation:
    <<: *deploy_template
    only:
        changes:
            - simulation/**/*
        
deploy_trip:
    <<: *deploy_template
    only:
        changes:
            - trip/**/*
        
deploy_vehicle:
    <<: *deploy_template
    only:
        changes:
            - vehicle/**/*
